import { CanvasNode, Connection } from '@/components/canvas/DesignCanvas';

export interface ReferenceArchitecture {
  id: string;
  title: string;
  company: string;
  icon: string;
  difficulty: 'easy' | 'medium' | 'hard';
  description: string;
  tags: string[];
  nodeCount: number;
  connectionCount: number;
  nodes: CanvasNode[];
  connections: Connection[];
  annotations: { title: string; body: string }[];
}

export const REFERENCE_ARCHITECTURES: ReferenceArchitecture[] = [
  {
    id: 'netflix-streaming',
    title: 'Video Streaming Platform',
    company: 'Netflix',
    icon: 'play_circle',
    difficulty: 'hard',
    description: 'A globally distributed video streaming architecture handling millions of concurrent viewers with adaptive bitrate streaming, edge caching, and microservice orchestration.',
    tags: ['CDN', 'Microservices', 'Event-Driven', 'Global Scale'],
    nodeCount: 14,
    connectionCount: 16,
    nodes: [
      { id: 'n1', type: 'Client', icon: 'smartphone', x: 80, y: 300, label: 'Client Apps' },
      { id: 'n2', type: 'CDN', icon: 'public', x: 280, y: 200, label: 'Open Connect CDN' },
      { id: 'n3', type: 'DNS', icon: 'language', x: 280, y: 400, label: 'DNS Router' },
      { id: 'n4', type: 'LB', icon: 'alt_route', x: 480, y: 300, label: 'ELB' },
      { id: 'n5', type: 'Gateway', icon: 'router', x: 680, y: 300, label: 'Zuul API Gateway' },
      { id: 'n6', type: 'Server', icon: 'dns', x: 880, y: 150, label: 'Playback Service' },
      { id: 'n7', type: 'Server', icon: 'dns', x: 880, y: 300, label: 'User Profile Service' },
      { id: 'n8', type: 'Server', icon: 'dns', x: 880, y: 450, label: 'Recommendation Engine' },
      { id: 'n9', type: 'Cache', icon: 'bolt', x: 1080, y: 150, label: 'EVCache' },
      { id: 'n10', type: 'NoSQL', icon: 'view_cozy', x: 1080, y: 300, label: 'Cassandra' },
      { id: 'n11', type: 'SQL', icon: 'database', x: 1080, y: 450, label: 'MySQL' },
      { id: 'n12', type: 'Kafka', icon: 'hub', x: 680, y: 520, label: 'Kafka Bus' },
      { id: 'n13', type: 'Blob', icon: 'folder_zip', x: 480, y: 100, label: 'S3 Video Store' },
      { id: 'n14', type: 'Metrics', icon: 'monitoring', x: 680, y: 100, label: 'Atlas Metrics' },
    ],
    connections: [
      { id: 'c1', from: 'n1', to: 'n3', label: 'DNS lookup' },
      { id: 'c2', from: 'n3', to: 'n2', label: 'resolve edge' },
      { id: 'c3', from: 'n1', to: 'n2', label: 'stream video' },
      { id: 'c4', from: 'n2', to: 'n13', label: 'origin pull' },
      { id: 'c5', from: 'n1', to: 'n4', label: 'API calls' },
      { id: 'c6', from: 'n4', to: 'n5' },
      { id: 'c7', from: 'n5', to: 'n6' },
      { id: 'c8', from: 'n5', to: 'n7' },
      { id: 'c9', from: 'n5', to: 'n8' },
      { id: 'c10', from: 'n6', to: 'n9', label: 'session cache' },
      { id: 'c11', from: 'n7', to: 'n10', label: 'user data' },
      { id: 'c12', from: 'n8', to: 'n11', label: 'ML models' },
      { id: 'c13', from: 'n6', to: 'n12', label: 'view events' },
      { id: 'c14', from: 'n7', to: 'n12', label: 'profile events' },
      { id: 'c15', from: 'n12', to: 'n8', label: 'consume' },
      { id: 'c16', from: 'n5', to: 'n14', label: 'telemetry' },
    ],
    annotations: [
      { title: 'Open Connect CDN', body: 'Netflix operates its own CDN with appliances embedded in ISPs worldwide, serving 95% of video traffic from local caches.' },
      { title: 'EVCache', body: 'A distributed caching solution built on Memcached that handles millions of reads/sec for session and metadata lookups.' },
      { title: 'Event-Driven Pipeline', body: 'Kafka acts as the central nervous system, decoupling services and enabling real-time analytics and recommendations.' },
    ],
  },
  {
    id: 'uber-dispatch',
    title: 'Ride-Sharing Dispatch System',
    company: 'Uber',
    icon: 'local_taxi',
    difficulty: 'hard',
    description: 'A real-time dispatch system matching riders with drivers using geospatial indexing, supply prediction, and low-latency WebSocket communication.',
    tags: ['Geospatial', 'Real-Time', 'WebSocket', 'Supply/Demand'],
    nodeCount: 13,
    connectionCount: 14,
    nodes: [
      { id: 'u1', type: 'Client', icon: 'smartphone', x: 80, y: 200, label: 'Rider App' },
      { id: 'u2', type: 'Client', icon: 'smartphone', x: 80, y: 450, label: 'Driver App' },
      { id: 'u3', type: 'LB', icon: 'alt_route', x: 300, y: 320, label: 'Load Balancer' },
      { id: 'u4', type: 'Gateway', icon: 'router', x: 500, y: 320, label: 'API Gateway' },
      { id: 'u5', type: 'Server', icon: 'dns', x: 720, y: 150, label: 'Trip Service' },
      { id: 'u6', type: 'Server', icon: 'dns', x: 720, y: 320, label: 'Dispatch Engine' },
      { id: 'u7', type: 'Server', icon: 'dns', x: 720, y: 490, label: 'Location Service' },
      { id: 'u8', type: 'Cache', icon: 'bolt', x: 940, y: 320, label: 'Geospatial Index' },
      { id: 'u9', type: 'NoSQL', icon: 'view_cozy', x: 940, y: 150, label: 'Trip Store' },
      { id: 'u10', type: 'SQL', icon: 'database', x: 940, y: 490, label: 'User/Driver DB' },
      { id: 'u11', type: 'Kafka', icon: 'hub', x: 500, y: 520, label: 'Event Stream' },
      { id: 'u12', type: 'WebSocket', icon: 'sync_alt', x: 300, y: 150, label: 'WS Gateway' },
      { id: 'u13', type: 'Metrics', icon: 'monitoring', x: 500, y: 100, label: 'Observability' },
    ],
    connections: [
      { id: 'uc1', from: 'u1', to: 'u3', label: 'request ride' },
      { id: 'uc2', from: 'u2', to: 'u3', label: 'location updates' },
      { id: 'uc3', from: 'u3', to: 'u4' },
      { id: 'uc4', from: 'u4', to: 'u5' },
      { id: 'uc5', from: 'u4', to: 'u6' },
      { id: 'uc6', from: 'u4', to: 'u7' },
      { id: 'uc7', from: 'u6', to: 'u8', label: 'geo query' },
      { id: 'uc8', from: 'u5', to: 'u9', label: 'persist trip' },
      { id: 'uc9', from: 'u7', to: 'u10', label: 'driver state' },
      { id: 'uc10', from: 'u7', to: 'u11', label: 'location events' },
      { id: 'uc11', from: 'u11', to: 'u6', label: 'consume' },
      { id: 'uc12', from: 'u12', to: 'u1', label: 'push updates' },
      { id: 'uc13', from: 'u12', to: 'u2', label: 'push updates' },
      { id: 'uc14', from: 'u6', to: 'u12', label: 'match result' },
    ],
    annotations: [
      { title: 'Geospatial Index (H3)', body: 'Uber uses an H3 hexagonal grid to partition the world, enabling O(1) nearest-driver lookups within a hex cell.' },
      { title: 'Dispatch Engine', body: 'Core matching service that balances supply/demand, calculates ETAs, and assigns optimal driver-rider pairs in under 500ms.' },
      { title: 'WebSocket Gateway', body: 'Maintains persistent connections to millions of driver/rider apps, enabling sub-second push notifications for trip updates.' },
    ],
  },
  {
    id: 'twitter-timeline',
    title: 'Social Feed / Timeline',
    company: 'Twitter (X)',
    icon: 'forum',
    difficulty: 'medium',
    description: 'A fan-out-on-write architecture for delivering personalized timelines to hundreds of millions of users with sub-second latency.',
    tags: ['Fan-Out', 'Cache', 'Timeline', 'Graph'],
    nodeCount: 11,
    connectionCount: 12,
    nodes: [
      { id: 't1', type: 'Client', icon: 'smartphone', x: 80, y: 300, label: 'Client' },
      { id: 't2', type: 'LB', icon: 'alt_route', x: 280, y: 300, label: 'Load Balancer' },
      { id: 't3', type: 'Server', icon: 'dns', x: 480, y: 200, label: 'Write Path' },
      { id: 't4', type: 'Server', icon: 'dns', x: 480, y: 400, label: 'Read Path' },
      { id: 't5', type: 'Queue', icon: 'mail', x: 680, y: 200, label: 'Fan-Out Queue' },
      { id: 't6', type: 'Worker', icon: 'precision_manufacturing', x: 880, y: 200, label: 'Fan-Out Worker' },
      { id: 't7', type: 'Cache', icon: 'bolt', x: 880, y: 400, label: 'Timeline Cache' },
      { id: 't8', type: 'SQL', icon: 'database', x: 680, y: 400, label: 'Tweet Store' },
      { id: 't9', type: 'GraphDB', icon: 'share', x: 1080, y: 200, label: 'Social Graph' },
      { id: 't10', type: 'Search', icon: 'saved_search', x: 1080, y: 400, label: 'Search Index' },
      { id: 't11', type: 'CDN', icon: 'public', x: 280, y: 150, label: 'Media CDN' },
    ],
    connections: [
      { id: 'tc1', from: 't1', to: 't2' },
      { id: 'tc2', from: 't2', to: 't3', label: 'write tweet' },
      { id: 'tc3', from: 't2', to: 't4', label: 'read timeline' },
      { id: 'tc4', from: 't3', to: 't8', label: 'persist' },
      { id: 'tc5', from: 't3', to: 't5', label: 'enqueue fan-out' },
      { id: 'tc6', from: 't5', to: 't6' },
      { id: 'tc7', from: 't6', to: 't9', label: 'get followers' },
      { id: 'tc8', from: 't6', to: 't7', label: 'push to caches' },
      { id: 'tc9', from: 't4', to: 't7', label: 'read cache' },
      { id: 'tc10', from: 't3', to: 't10', label: 'index tweet' },
      { id: 'tc11', from: 't4', to: 't8', label: 'cache miss' },
      { id: 'tc12', from: 't1', to: 't11', label: 'media' },
    ],
    annotations: [
      { title: 'Fan-Out on Write', body: 'When a user tweets, a worker reads their follower list and pushes the tweet ID into each follower\'s cached timeline. This makes reads O(1) but writes O(N).' },
      { title: 'Hybrid Approach', body: 'Celebrity accounts with millions of followers use fan-out-on-read instead, merging their tweets at query time to avoid overwhelming the write path.' },
      { title: 'Timeline Cache', body: 'Redis-backed sorted sets hold the last ~800 tweet IDs per user, enabling sub-10ms timeline reads.' },
    ],
  },
  {
    id: 'stripe-payments',
    title: 'Payment Processing Pipeline',
    company: 'Stripe',
    icon: 'payments',
    difficulty: 'hard',
    description: 'A fault-tolerant payment processing system with idempotent operations, saga orchestration, and PCI-compliant data isolation.',
    tags: ['Idempotency', 'Saga', 'PCI-DSS', 'Exactly-Once'],
    nodeCount: 12,
    connectionCount: 13,
    nodes: [
      { id: 's1', type: 'Client', icon: 'smartphone', x: 80, y: 300, label: 'Merchant Client' },
      { id: 's2', type: 'Firewall', icon: 'local_fire_department', x: 280, y: 300, label: 'WAF / DDoS Shield' },
      { id: 's3', type: 'Gateway', icon: 'router', x: 480, y: 300, label: 'API Gateway' },
      { id: 's4', type: 'Server', icon: 'dns', x: 680, y: 200, label: 'Payment Intent Service' },
      { id: 's5', type: 'Server', icon: 'dns', x: 680, y: 420, label: 'Charge Service' },
      { id: 's6', type: 'Auth', icon: 'passkey', x: 480, y: 130, label: 'Auth / Tokenization' },
      { id: 's7', type: 'SQL', icon: 'database', x: 900, y: 200, label: 'Ledger DB (PCI Zone)' },
      { id: 's8', type: 'Queue', icon: 'mail', x: 900, y: 420, label: 'Retry Queue' },
      { id: 's9', type: 'Server', icon: 'dns', x: 1100, y: 300, label: 'Bank Connector' },
      { id: 's10', type: 'Vault', icon: 'lock', x: 480, y: 480, label: 'Secret Vault' },
      { id: 's11', type: 'Kafka', icon: 'hub', x: 680, y: 550, label: 'Event Log' },
      { id: 's12', type: 'Logger', icon: 'receipt_long', x: 900, y: 550, label: 'Audit Trail' },
    ],
    connections: [
      { id: 'sc1', from: 's1', to: 's2' },
      { id: 'sc2', from: 's2', to: 's3' },
      { id: 'sc3', from: 's3', to: 's6', label: 'authenticate' },
      { id: 'sc4', from: 's3', to: 's4', label: 'create intent' },
      { id: 'sc5', from: 's4', to: 's7', label: 'record' },
      { id: 'sc6', from: 's4', to: 's5', label: 'execute charge' },
      { id: 'sc7', from: 's5', to: 's9', label: 'submit to bank' },
      { id: 'sc8', from: 's5', to: 's8', label: 'on failure: retry' },
      { id: 'sc9', from: 's8', to: 's5', label: 'dequeue' },
      { id: 'sc10', from: 's9', to: 's7', label: 'settlement' },
      { id: 'sc11', from: 's5', to: 's11', label: 'charge events' },
      { id: 'sc12', from: 's11', to: 's12', label: 'persist' },
      { id: 'sc13', from: 's3', to: 's10', label: 'fetch keys' },
    ],
    annotations: [
      { title: 'Idempotency Keys', body: 'Every API call carries an idempotency key. The Payment Intent Service deduplicates retries by checking the key against the Ledger DB before executing.' },
      { title: 'PCI Data Isolation', body: 'Card numbers never leave the PCI Zone. Tokenization at the edge converts sensitive data into opaque tokens that flow through non-PCI services.' },
      { title: 'Saga Orchestration', body: 'The Charge Service orchestrates a distributed saga: authorize → capture → settle, with compensating actions on any step failure.' },
    ],
  },
  {
    id: 'slack-messaging',
    title: 'Real-Time Messaging Platform',
    company: 'Slack',
    icon: 'chat',
    difficulty: 'medium',
    description: 'A real-time messaging system handling billions of messages with presence tracking, search indexing, and persistent WebSocket connections.',
    tags: ['WebSocket', 'Presence', 'Search', 'Channels'],
    nodeCount: 11,
    connectionCount: 12,
    nodes: [
      { id: 'sl1', type: 'Client', icon: 'smartphone', x: 80, y: 300, label: 'Desktop / Mobile' },
      { id: 'sl2', type: 'LB', icon: 'alt_route', x: 280, y: 300, label: 'Load Balancer' },
      { id: 'sl3', type: 'WebSocket', icon: 'sync_alt', x: 480, y: 200, label: 'WS Connection Mgr' },
      { id: 'sl4', type: 'Server', icon: 'dns', x: 480, y: 420, label: 'Message Service' },
      { id: 'sl5', type: 'Cache', icon: 'bolt', x: 700, y: 200, label: 'Presence Cache' },
      { id: 'sl6', type: 'SQL', icon: 'database', x: 700, y: 420, label: 'MySQL (Vitess)' },
      { id: 'sl7', type: 'PubSub', icon: 'cell_tower', x: 700, y: 560, label: 'Channel PubSub' },
      { id: 'sl8', type: 'Search', icon: 'saved_search', x: 920, y: 300, label: 'Elasticsearch' },
      { id: 'sl9', type: 'Blob', icon: 'folder_zip', x: 920, y: 420, label: 'File Storage' },
      { id: 'sl10', type: 'Queue', icon: 'mail', x: 920, y: 560, label: 'Notification Queue' },
      { id: 'sl11', type: 'Worker', icon: 'precision_manufacturing', x: 1120, y: 560, label: 'Push Worker' },
    ],
    connections: [
      { id: 'slc1', from: 'sl1', to: 'sl2' },
      { id: 'slc2', from: 'sl2', to: 'sl3', label: 'WS upgrade' },
      { id: 'slc3', from: 'sl2', to: 'sl4', label: 'HTTP API' },
      { id: 'slc4', from: 'sl3', to: 'sl5', label: 'heartbeat' },
      { id: 'slc5', from: 'sl4', to: 'sl6', label: 'persist msg' },
      { id: 'slc6', from: 'sl4', to: 'sl7', label: 'publish' },
      { id: 'slc7', from: 'sl7', to: 'sl3', label: 'fan-out' },
      { id: 'slc8', from: 'sl4', to: 'sl8', label: 'index' },
      { id: 'slc9', from: 'sl4', to: 'sl9', label: 'attachments' },
      { id: 'slc10', from: 'sl4', to: 'sl10', label: 'offline notify' },
      { id: 'slc11', from: 'sl10', to: 'sl11' },
      { id: 'slc12', from: 'sl11', to: 'sl1', label: 'push notification' },
    ],
    annotations: [
      { title: 'WebSocket Connection Manager', body: 'Maintains millions of persistent WS connections, routing messages to the correct client based on channel subscriptions and presence state.' },
      { title: 'Channel PubSub', body: 'Each Slack channel maps to a PubSub topic. When a message arrives, it is published to the topic and all subscribed WS managers fan it out to connected clients.' },
      { title: 'Vitess (MySQL Sharding)', body: 'Slack shards MySQL across thousands of instances using Vitess, partitioning data by workspace ID for horizontal scalability.' },
    ],
  },
  {
    id: 'url-shortener',
    title: 'URL Shortener Service',
    company: 'Bitly / TinyURL',
    icon: 'link',
    difficulty: 'easy',
    description: 'A high-throughput URL shortening service with redirect caching, analytics tracking, and base62 ID generation.',
    tags: ['Caching', 'Redirect', 'Analytics', 'High Read'],
    nodeCount: 9,
    connectionCount: 10,
    nodes: [
      { id: 'b1', type: 'Client', icon: 'smartphone', x: 80, y: 300, label: 'Browser' },
      { id: 'b2', type: 'CDN', icon: 'public', x: 280, y: 150, label: 'Edge CDN' },
      { id: 'b3', type: 'LB', icon: 'alt_route', x: 280, y: 300, label: 'Load Balancer' },
      { id: 'b4', type: 'Server', icon: 'dns', x: 500, y: 300, label: 'URL Service' },
      { id: 'b5', type: 'Cache', icon: 'bolt', x: 720, y: 200, label: 'Redis Cache' },
      { id: 'b6', type: 'NoSQL', icon: 'view_cozy', x: 720, y: 400, label: 'URL Store' },
      { id: 'b7', type: 'Kafka', icon: 'hub', x: 500, y: 480, label: 'Click Stream' },
      { id: 'b8', type: 'Worker', icon: 'precision_manufacturing', x: 720, y: 560, label: 'Analytics Worker' },
      { id: 'b9', type: 'SQL', icon: 'database', x: 940, y: 560, label: 'Analytics DB' },
    ],
    connections: [
      { id: 'bc1', from: 'b1', to: 'b2', label: 'redirect (cache hit)' },
      { id: 'bc2', from: 'b1', to: 'b3', label: 'shorten / redirect' },
      { id: 'bc3', from: 'b3', to: 'b4' },
      { id: 'bc4', from: 'b4', to: 'b5', label: 'lookup cache' },
      { id: 'bc5', from: 'b4', to: 'b6', label: 'cache miss' },
      { id: 'bc6', from: 'b4', to: 'b6', label: 'create short URL' },
      { id: 'bc7', from: 'b4', to: 'b7', label: 'click event' },
      { id: 'bc8', from: 'b7', to: 'b8' },
      { id: 'bc9', from: 'b8', to: 'b9', label: 'aggregate' },
      { id: 'bc10', from: 'b2', to: 'b4', label: 'origin' },
    ],
    annotations: [
      { title: 'Base62 Encoding', body: 'Short codes are generated using base62 (a-zA-Z0-9) encoding of a distributed counter or hash, producing compact 6-7 character slugs.' },
      { title: 'Read-Heavy Optimization', body: '99% of traffic is reads (redirects). Hot URLs are cached at the CDN edge and in Redis, hitting the database only on cold starts.' },
      { title: 'Click Analytics Pipeline', body: 'Every redirect fires an event to Kafka, processed asynchronously by analytics workers without impacting redirect latency.' },
    ],
  },
];
