import mongoose, { Schema, Model, Document, Types } from 'mongoose';
import { ICanvasNode, IConnection } from './Design';

// Structured question generated by AI
export interface IInterviewQuestion {
    prompt: string;
    requirements: string[];
    constraints: string[];
    trafficProfile: {
        users?: string;
        rps?: string;
        storage?: string;
    };
    hints: string[];
}

// Individual rule result from structural evaluation
export interface IRuleResult {
    rule: string;
    status: 'pass' | 'fail';
    message: string;
    severity: 'critical' | 'warning' | 'info';
}

// Full evaluation result
export interface IEvaluation {
    structural: {
        score: number;
        passedRules: string[];
        failedRules: string[];
        details: IRuleResult[];
    };
    reasoning: {
        score: number;
        strengths: string[];
        weaknesses: string[];
        suggestions: string[];
    };
    finalScore: number;
    weights: {
        structural: number;
        reasoning: number;
    };
}

export type InterviewDifficulty = 'easy' | 'medium' | 'hard';
export type InterviewStatus = 'in_progress' | 'submitted' | 'evaluating' | 'evaluated';

export interface IInterviewSession extends Document {
    userId: Types.ObjectId;
    question: IInterviewQuestion;
    difficulty: InterviewDifficulty;
    timeLimit: number; // minutes
    startedAt: Date;
    submittedAt?: Date;
    status: InterviewStatus;
    canvasSnapshot: {
        nodes: ICanvasNode[];
        connections: IConnection[];
    };
    evaluation?: IEvaluation;
    createdAt: Date;
    updatedAt: Date;
}

// --- Schemas ---

const TrafficProfileSchema = new Schema(
    {
        users: { type: String },
        rps: { type: String },
        storage: { type: String },
    },
    { _id: false }
);

const InterviewQuestionSchema = new Schema(
    {
        prompt: { type: String, required: true },
        requirements: { type: [String], default: [] },
        constraints: { type: [String], default: [] },
        trafficProfile: { type: TrafficProfileSchema, default: {} },
        hints: { type: [String], default: [] },
    },
    { _id: false }
);

const RuleResultSchema = new Schema(
    {
        rule: { type: String, required: true },
        status: { type: String, enum: ['pass', 'fail'], required: true },
        message: { type: String, required: true },
        severity: { type: String, enum: ['critical', 'warning', 'info'], required: true },
    },
    { _id: false }
);

const StructuralEvalSchema = new Schema(
    {
        score: { type: Number, required: true },
        passedRules: { type: [String], default: [] },
        failedRules: { type: [String], default: [] },
        details: { type: [RuleResultSchema], default: [] },
    },
    { _id: false }
);

const ReasoningEvalSchema = new Schema(
    {
        score: { type: Number, required: true },
        strengths: { type: [String], default: [] },
        weaknesses: { type: [String], default: [] },
        suggestions: { type: [String], default: [] },
    },
    { _id: false }
);

const EvaluationSchema = new Schema(
    {
        structural: { type: StructuralEvalSchema, required: true },
        reasoning: { type: ReasoningEvalSchema, required: true },
        finalScore: { type: Number, required: true },
        weights: {
            structural: { type: Number, required: true },
            reasoning: { type: Number, required: true },
        },
    },
    { _id: false }
);

const CanvasSnapshotNodeSchema = new Schema(
    {
        id: { type: String, required: true },
        type: { type: String, required: true },
        icon: { type: String, required: true },
        x: { type: Number, required: true },
        y: { type: Number, required: true },
        label: { type: String },
    },
    { _id: false }
);

const CanvasSnapshotConnectionSchema = new Schema(
    {
        id: { type: String, required: true },
        from: { type: String, required: true },
        to: { type: String, required: true },
    },
    { _id: false }
);

const InterviewSessionSchema = new Schema<IInterviewSession>(
    {
        userId: {
            type: Schema.Types.ObjectId,
            ref: 'User',
            required: true,
            index: true,
        },
        question: {
            type: InterviewQuestionSchema,
            required: true,
        },
        difficulty: {
            type: String,
            enum: ['easy', 'medium', 'hard'],
            required: true,
        },
        timeLimit: {
            type: Number,
            required: true,
            default: 45,
        },
        startedAt: {
            type: Date,
            required: true,
            default: Date.now,
        },
        submittedAt: {
            type: Date,
            default: null,
        },
        status: {
            type: String,
            enum: ['in_progress', 'submitted', 'evaluating', 'evaluated'],
            default: 'in_progress',
        },
        canvasSnapshot: {
            nodes: { type: [CanvasSnapshotNodeSchema], default: [] },
            connections: { type: [CanvasSnapshotConnectionSchema], default: [] },
        },
        evaluation: {
            type: EvaluationSchema,
            default: null,
        },
    },
    {
        timestamps: true,
    }
);

// Indexes for efficient queries
InterviewSessionSchema.index({ userId: 1, createdAt: -1 });
InterviewSessionSchema.index({ userId: 1, status: 1 });

const InterviewSession: Model<IInterviewSession> =
    mongoose.models.InterviewSession ||
    mongoose.model<IInterviewSession>('InterviewSession', InterviewSessionSchema);

export default InterviewSession;
