apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-craft
  labels:
    app: system-craft
spec:
  replicas: 3
  selector:
    matchLabels:
      app: system-craft
  template:
    metadata:
      labels:
        app: system-craft
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - name: system-craft
        image: ghcr.io/shashank0701-byte/system-craft/systemcraft-web:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri