apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: system-craft-hpa
  labels:
    app: system-craft
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: system-craft
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 4
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
