{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "systemcraft.fullname" . }}-monitor
  labels:
    {{- include "systemcraft.labels" . | nindent 4 }}
    release: {{ .Values.serviceMonitor.releaseLabel }}
spec:
  selector:
    matchLabels:
      {{- include "systemcraft.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
